### ISSUE TITLE
Question on permissions

### ISSUE THREAD

**Issue by IzzySoft** [deltalab-org/deltalab-android#15]
My APK scanner got a few additional checks implemented in January, and on today's release of Delta reported:

```
! repo/chat.delta.lite_30000669.apk declares sensitive permission(s):
 android.permission.READ_CONTACTS android.permission.READ_MEDIA_IMAGES
 android.permission.READ_MEDIA_VIDEO android.permission.READ_EXTERNAL_STORAGE
 android.permission.CAMERA android.permission.ACCESS_BACKGROUND_LOCATION
 android.permission.ACCESS_COARSE_LOCATION android.permission.ACCESS_FINE_LOCATION
 android.permission.RECORD_AUDIO android.permission.REQUEST_INSTALL_PACKAGES
```

Now, some of those I thought to be clear and added them already to the app's allow list (to make the explanations visible and reduce the warning reports for the next round):

![image](https://github.com/deltalab-org/deltalab-android/assets/6781438/4706511f-cc6a-474a-bd4b-893c1f09cc1f)

(please correct me should I've gotten something wrong there), but a few "chocolate entries" are still open. Could you please clarify what the location permissions are needed for – and what packages Delta tries to install? Be welcome to include explanations for the others as well to make them transparent, too :wink:

As for the `DEPENDENCY_INFO_BLOCK`, that should be easy to get rid of:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains.

Thanks in advance!

**Comment by adbenitez** [comment]
hi, thanks for reaching out, nice to see your apk scanner got improved

> please clarify what the location permissions are needed for

DeltaLab has a "location streaming" feature, where user can share their location with a group or contact, the permission is asked only when the user actually request to use such features

> and what packages Delta tries to install

DeltaLab doesn't install any apk, I am not sure since that permission comes from upstream Delta Chat, but IIRC it is about allowing user to install APKs received, ex. some friend directly sent you in an encrypted chat an APK file and then you click the attachment and then the package installer of the system offers to install the apk, similar to browsers and downloaded APKs I think the permission is about the app being a possible source of APKs, not that the app can install APKs in background without the permissions of the user, so in short: the reason is the same as for browsers, to install downloaded apks (in this case received by encrypted email instead of the web)

**Comment by IzzySoft** [comment]
`CAMERA` is still there with today's release:

    ! repo/chat.delta.lite_30000672.apk declares sensitive permission(s): android.permission.CAMERA

But the BLOB is gone :partying_face:

**Comment by adbenitez** [comment]
> `CAMERA` is still there with today's release:

I have no clue why, I removed the permission from AndroidManifest.xml file as you can review in the linked PR so I don't know how is it even possible that it still has the camera permission

**Comment by IzzySoft** [comment]
I have a [vague clue](https://github.com/deltalab-org/deltalab-android/blob/main/AndroidManifest.xml#L5):

```xml
<uses-feature android:name="android.hardware.camera" android:required="false" />
```

Not sure about the `required`, but declaring that feature would IIRC implicitly trigger the permission. Maybe remove that line, build an APK, and run `aapt d badging app-release.apk` to check? If that does the trick, we have identified the culprit.

**Comment by adbenitez** [comment]
> I have a [vague clue](https://github.com/deltalab-org/deltalab-android/blob/main/AndroidManifest.xml#L5):

no luck, tried removing this from manifest, then running the aapt command you recommended and grep-ing for camera:
```
uses-permission: name='android.permission.CAMERA'
  uses-feature-not-required: name='android.hardware.camera'
  uses-feature-not-required: name='android.hardware.camera.autofocus'
  uses-feature-not-required: name='android.hardware.camera.flash'
  uses-feature-not-required: name='android.hardware.camera.front'
```

**Comment by adbenitez** [comment]
mmmh... oth, I think this "no need camera permission to take pictures" was a feature added on recent android versions? :thinking: we support android 4, I would not like to break things for them, I think I will revert even the camera permission request in manifest just in case, I think for those devices is needed IIRC

**Comment by adbenitez** [comment]
UPDATE: camera permission is actually needed, the app has a QR scanner, that needs direct access to camera, unlike the "take photo to attach" feature

**Comment by IzzySoft** [comment]
> the app has a QR scanner

Now, that's an easy explanation indeed! Added – and the last piece of chocolate is gone:

![image](https://github.com/deltalab-org/deltalab-android/assets/6781438/9c5af855-97bf-4a8d-81fb-b73a0ff138f9)

Be welcome to name descriptions for any of the permissions left if you want – or to close the issue then. Thanks a lot!

**Comment by adbenitez** [comment]
> Now, that's an easy explanation indeed! Added – and the last piece of chocolate is gone:

thanks a lot for your help!, btw, for me the permissions still look in "chocolate" color at https://apt.izzysoft.de/fdroid/index/apk/chat.delta.lite

**Comment by IzzySoft** [comment]
> for me the permissions still look in "chocolate" color

Nonono. Look again, the sync was at 7 pm UTC as usual :wink: (and apologies, I must have forgotten to sync that file manually, which for this would have worked… Too many of those issues to follow currently, since my scanner got those additional checks. Hope that will calm down a bit soon…)
