### ISSUE TITLE
proprietary components were added with the latest release

### ISSUE THREAD

**Issue by IzzySoft** [deltalab-org/deltalab-android#19]
With the last release, the APK provided contains:

```
Offending libs:
---------------
* Firebase Data Transport (/com/google/android/datatransport): NonFreeNet
* Google Mobile Services (/com/google/android/gms): NonFreeComp
* Firebase (/com/google/firebase): NonFreeNet,NonFreeComp
* Firebase Installations (/com/google/firebase/installations): NonFreeNet

4 offenders.
```

Which basically means the app is no longer fully libre, and I'll now have to add at least the two mentioned anti-features. Was this change intended? Is there a chance to make the app fully F/LOSS again?

**Comment by adbenitez** [comment]
hi, the change was added to upstream Delta Chat to support Push Notifications (no data is sent just dummy empty push notifications to wake up the app to avoid systems killing the app in background and then not being able to receive notification until you open it)

the library is striped from the analytics component, also the whole feature is not used if you use a de-googled phone, it is only used if you already have push notifications service or microG

it is also possible to disable it in the settings

I was not aware the lib was not free software, for now I am fine with the anti-features, since receiving notifications in time is more important and not worse if you already have a a device with Push Notifications enabled

**Comment by IzzySoft** [comment]
> receiving notifications in time is more important

We're talking about FOSS here, so keeping it FOSS should be one of the priorities. And FCM is not the only way to get those notifications, there's always @UnifiedPush (which btw. also has support for FCM if you need that). UP works fine here with e.g. [NTFY](https://ntfy.sh/).

> and not worse if you already have a a device with Push Notifications enabled

I prefer giving people motivation to leave those proprietary walled gardens behind. If even FOSS apps bind themselves to those, that just makes it harder to leave as there's again one more thing that would "stop working" :wink:

I also wonder why Delta is doing that. Are there too many email servers not supporting IMAP IDLE?

**Comment by adbenitez** [comment]
> I also wonder why Delta is doing that. Are there too many email servers not supporting IMAP IDLE?

in fact, IMAP IDLE works fine BUT Android system is aggressive and kills app in background not allowing email clients to keep the lightweight socket connection to the IMAP server

> We're talking about FOSS here, so keeping it FOSS should be one of the priorities

it is, but it is also my priority that people AT LEAST use free software apps instead of full private ones, in practice if my app fails to deliver messages in time what happens is that people uninstall it and use WhatsApp et al., my target is not a small bunch of purist nerds, but main stream masses, if you are a true purist you should not even have your store supporting Android at all, you are promoting Google's system, applying your logic: why not make it harder so people go right for Replicant or even better some Linux phone like the pinephone? I think we both are here because this is a better first step towards the final goal.



> And FCM is not the only way to get those notifications, there's always @UnifiedPush (which btw. also has support for FCM if you need that).

this is simply impractical, I can not go around telling people to install unified push to then use FCM anyway in the end, there is no point in using Unified Push at all in this case, its use case is for another situations IIRC

**Comment by IzzySoft** [comment]
I get your points, thanks. We're on the same road here just in slightly different vehicles it seems. If you permit me a last "idea": those differences *could* be solved via build flavors and offering the corresponding APKs for both variants – so everyone could pick according to their preference.

> if you are a true purist

"Lord, let me be pure – but not yet…" :speak_no_evil: Going by that we'd have to drop all and go "back to the roots", yes. Finding the right balance is not easy – and (full ack) also quite a bit subjective. I cannot tell what balance others shall seek, that's not for me to decide. I just can decide that for myself – and make suggestions here and there :wink:

> telling people to install unified push to then use FCM anyway in the end

IIRC there was a way to integrate a FOSS variant of FCM with UP, which then would reduce the anti-features to just "NonFreeNet". But implementation is a bit beyond me, as I'm no Android dev…

**Comment by adbenitez** [comment]
> IIRC there was a way to integrate a FOSS variant of FCM with UP

if there were some alternative lib for FCM that would avoid shipping privative blobs and only connect to the google servers similar to what microG does that would be great, then we could use it directly in the app, once again no need to use Unified Push


> those differences _could_ be solved via build flavors

at the moment there is a single release of DeltaLab, I may try to go for play store, then it would make sense to have two flavors: one all down the lost path in google play (if you are using google play anyway you are already in the "dark side") and then a more "clean" variant in izzyondroid without push notifications and relaying on a permanent notification then

all this is a bit of an effort for me since I maintain DeltaLab for free on the side without deep knowledge in Android building and shipping to Google Play, while at the same time contributing to official DC and several other projects

thanks for your reply, time and care! :pray:

**Comment by adbenitez** [comment]
I found the docs about the open source library: https://unifiedpush.org/developers/embedded_fcm/

> There are 2 libraries doing it: one using the Google Firebase library and another (beta) entirely FOSS[*](https://en.wikipedia.org/wiki/FOSS) that doesn’t.
> ...
> The [Android FOSS Embedded FCM Distributor](https://github.com/UnifiedPush/android-foss_embedded_fcm_distributor) is a new library. It reimplements the same API that the Google library uses. Since it’s open source, it can be used on FOSS app stores like F-Droid.

sadly it is a beta but that is quite promising! if I got it correctly it will work with unified push if present and only fallback to google's FCM as last resort with at least open source client library code

**Comment by IzzySoft** [comment]
> if there were some alternative lib for FCM that would avoid shipping privative blobs and only connect to the google servers similar to what microG does that would be great

There definitely is. One such implementation is being used by the official Mastodon client (and thus also by its forks), consisting of very few lines of code. Another was mentioned by UP themselves, but I'm not sure about the details of that implementation. While I type this your new comment shows up; I see you've found this one already:

> if I got it correctly it will work with unified push if present and only fallback to google's FCM as last resort with at least open source client library code

That was my understanding, yes. And that would be kinda ideal, as it would rid you of the NonFreeNet as well (especially when made optional and opt-in, e.g. with a question during onboarding and a possibility to switch in the settings).

> once again no need to use Unified Push

Just leaving the – what did you call them? Ah: "small bunch of purist nerds" out then, but yeah, better than shipping the blobs, that's true.

> I may try to go for play store, then it would make sense to have two flavors

Yupp. Good idea to leave that in the todo list for when that time comes, and dig into details then. Who knows what options might have shown up until then – maybe some easy drop-in replacement with identical interfaces, which would make this a breeze… (well, one can dream, right?)

> thanks for your reply, time and care! 🙏

Gladly – and same to you as well! :hugs:

**Comment by adbenitez** [comment]
> Just leaving the – what did you call them? Ah: "small bunch of purist nerds" out then, but yeah, better than shipping the blobs, that's true.

I think it is just the wrong approach, you rather are an user without much tech knowledge and with a google phone with push notifications or you are more on the freedom side and would go for a better phone with LineageOS, CalyxOS etc. there you don't need push notifications at all and can let the app work in background since as you said IMAP IDLE exist since ages and there is no need for this push notifications non-sense, I understand that unified push is necessary for other fancy apps that tried to reinvent the wheel and replace email, but that is not the case for good old email protocols in the end...

**Comment by adbenitez** [comment]
hi @IzzySoft, the issue is solved, now the released FOSS file is `deltalab-foss-1.46.13.apk` in the releases pages, I guess you have to update the script that fetches the apk, thanks a lot!

**Comment by IzzySoft** [comment]
I would check, but the armeabi build is missing at the releases since 1.46.8 (where it was attached last). The FAT build is exceeding the per-app size limit at IoD if you remember :wink:

**Comment by adbenitez** [comment]
hi @IzzySoft, so I gave it a try to go for the official F-Droid repo (more devices support, more discoverability) and managed to make it so the apk can be checked with reproducible builds by F-Droid so I can still sign the app like on IoD!

https://gitlab.com/fdroid/fdroiddata/-/merge_requests/15640

while the split apks are back on releases page, I guess what is needed to do now is to remove it from IoD, since that would be a waste of space in IoD server, thanks a lot for hosting the app all this time! (since 2022!) :heart:

**Comment by IzzySoft** [comment]
Congrats to your RB with F-Droid! No idea what your script is doing there (e.g. `mv "$fdroiddir" "$repo"` – where does that dir come from?) – but when I try using your script I hopelessly fail:

```yaml
        build:
          - git clone https://github.com/rust-lang/rustup.git -b 1.25.1
          - export ANDROID_NDK_ROOT=/opt/sdk/ndk/${PROVISIONING_NDK}
          - scripts/ndk-make-fdroid.sh ${BUILD_REPO_DIR}/rustup ${ANDROID_NDK_ROOT} armeabi-v7a
```

Fails with

```
source "$HOME/.cargo/env.fish"  # For fish
starting time: Wed Aug 28 23:26:14 UTC 2024
ANDROID_NDK_ROOT is not set
```

after having successfully set up rust, despite it being explicitly exported. Building via your gradle setup on the other hand works, but seems to skip the rust part, so the APK generated is incomplete.

> I guess what is needed to do now is to remove it from IoD

The time that we remove apps from IoD just because they become available at F-Droid ended with the year 2023 (at the time I [stopped being active at F-Droid](https://gitlab.com/fdroid/admin/-/issues/447)). If you want us to remove it, we'll of course comply – but otherwise the app can stay. If we can manage to build the APK, it would even get the "green shield" whenever it is RB, but that's optional here (and a failed RB wouldn't stop the APK to be shipped in-time, as you're used to with IoD). So: your choice :wink:

**Comment by adbenitez** [comment]
> e.g. `mv "$fdroiddir" "$repo"` – where does that dir come from?

the $fdroiddir var is defined some lines above it is just the folder fdroid CI creates to clone the git repo


> ANDROID_NDK_ROOT is not set

indeed there was a bug in the script, it just worked because the variable name casually matched `$NDK` var set/exported by the fdroid pipeline, I pushed a fix

> but otherwise the app can stay.

there is no extra work for me since I need to provide the apk files anyway and they are the same APK files I was already publishing (same app id etc) so there is no damage if you think it still make sense to provide it on IoD (at least the releases will hit IoD faster than official fdroid so I guess that is still one advantage)

**Comment by adbenitez** [comment]
> And while the build seems to succeed, there's no APK to be found anywhere:

that script is only to build ArcaneChat's core (native library compiled with Rust)


anyway I simplified the process and now there is no ndk-make-fdroid.sh script anymore with f-droid specific stuff all the data is in the .yml configuration file in fdroid metadata repo, there, there is a gradle section that implies that gradle needs to be used to generate the apk

**Comment by adbenitez** [comment]
btw, I just realized the OpenCollective link in the app metadata on IoD is wrong it points to https://opencollective.com/delata-chat instead of https://opencollective.com/delta-chat

**Comment by IzzySoft** [comment]
> anyway I simplified the process and now there is no ndk-make-fdroid.sh script anymore with f-droid specific stuff

OK, let me give that a try. Umpf, wait: 1.46.16, created 2 pm UTC? How can that be if it was already there at 7:30 am UTC? Did you re-use the tag?

After playing a little with it I managed to build. But despite of specifying armeabi as you indicated:

```
BUILD SUCCESSFUL in 2m 53s
39 actionable tasks: 39 executed
+ find . -name '*.apk'
./build/outputs/apk/foss/release/ArcaneChat-foss-armeabi-v7a-unsigned-1.46.16.apk
./build/outputs/apk/foss/release/ArcaneChat-foss-x86_64-unsigned-1.46.16.apk
./build/outputs/apk/foss/release/ArcaneChat-foss-x86-unsigned-1.46.16.apk
./build/outputs/apk/foss/release/ArcaneChat-foss-arm64-v8a-unsigned-1.46.16.apk
./build/outputs/apk/foss/release/ArcaneChat-foss-universal-unsigned-1.46.16.apk
```

If I disable the unwanted ones

    sed -r '/abi \{/,/}/ { s/include.*/include "armeabi-v7a"/ ; s/universalApk true/universalApk false/ }' -i build.gradle

build fails:

```
> Conflicting configuration : 'armeabi-v7a,x86_64,arm64-v8a,x86' in ndk abiFilters cannot be present when splits abi filters are set : armeabi-v7a
```

:man_shrugging: So I'll have to build all 4 ABIs plus the universal one just to grab the armeabi from the resulting APKs. But wait:

```gradle
if(project.hasProperty("ABI_FILTER")) {
```

OK, so not `ABI_FILTER=armeabi-v7a ./gradlew assembleFossRelease`, but rather `./gradlew assembleFossRelease -PABI_FILTER=armeabi-v7a` – property, not environment variable. And right, that does the trick: build successful, and RB confirmed :partying_face: In case you're curious (might wish to use [rbtlog](https://codeberg.org/obfusk/rbtlog) yourself for building your APKs), here's the working recipe:

```yaml
---
repository: https://github.com/ArcaneChat/android.git
updates: releases
versions:
  - tag: v1.46.16
    apks:
      - apk_pattern: ArcaneChat-foss-armeabi-v7a.*\.apk
        apk_url: https://github.com/ArcaneChat/android/releases/download/v1.46.16/ArcaneChat-foss-armeabi-v7a-1.46.16.apk
        build:
          - sed -r '/signingConfigs.release/d' -i build.gradle
          - git clone https://github.com/rust-lang/rustup.git -b 1.25.1
          - export ANDROID_NDK=/opt/sdk/ndk/${PROVISIONING_NDK}
          - ${BUILD_REPO_DIR}/rustup/rustup-init.sh -y --default-toolchain $(cat scripts/rust-toolchain) --target armv7-linux-androideabi
          - source $HOME/.cargo/env
          - scripts/ndk-make.sh armeabi-v7a
          - ./gradlew assembleFossRelease -PABI_FILTER=armeabi-v7a
          - mv build/outputs/apk/foss/release/ArcaneChat-foss-unsigned-*.apk /outputs/unsigned.apk
        build_home_dir: /home/runner
        build_repo_dir: /home/runner/work/android/android
        build_user: runner
        provisioning:
          android_home: /opt/sdk
          build_tools:
          cmake:
          cmdline_tools:
            version: '12.0'
            url: https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
            sha256: 2d2d50857e4eb553af5a6dc3ad507a17adf43d115264b1afc116f95c92e5e258
          extra_packages:
            - make
            - g++
            - cmake
          image: debian:bookworm-slim
          jdk: openjdk-17-jdk-headless
          ndk: 23.2.8568313
          platform:
          platform_tools:
          tools:
          verify_gradle_wrapper: true
```

This will probably fail once you switch to a different `rustup` version – so maybe that version should be grabbed from somewhere the way it is done for `--default-toolchain`?

As you seem to have replaced the tag, the green RB shield won't show up before the next release (the APK for 1.46.16 had already been distributed before you replaced the tag, so the two do not match – which is why one should not do that, but rather create a new tag/release; no folks might wonder why IoD ships a different APK then your releases show).

That said: thanks for your help with this! Now your app is RB on both sides, same AK used at all 3 sides, so cross-updates are possible. And people can choose where to get updates from as well as refine their decisions later :smiley: 

> the OpenCollective link in the app metadata on IoD

Thanks for pointing this out – fixed, effective with the next sync. Maybe take a look at [FUNDING.yml](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository)? That allows you to maintain donation URLs yourself :wink: Both F-Droid and IoD support it.

**Comment by adbenitez** [comment]
> OK, so not `ABI_FILTER=armeabi-v7a ./gradlew assembleFossRelease`, but rather `./gradlew assembleFossRelease -PABI_FILTER=armeabi-v7a` – property, not environment variable.

tut mir leid, indeed I misremembered, with the correct environment variable it is:
```
ORG_GRADLE_PROJECT_ABI_FILTER=armeabi-v7a ./gradlew assembleFossRelease
```

but in fact using `-P` flag also works since you are calling `./gradlew` directly and don't need to pass the property indirectly via env var

**Comment by IzzySoft** [comment]
(flag vs env) no prob. Luckily I've learned a thing or two since I started setting up recipes for RB, and do not depend on "blind copies" :stuck_out_tongue_winking_eye: 

(FUNDING.yml) that file will be checked for on each release. But as its values are overwritten by what's explicitly specified in the app's metadata, please let me know when you've set it up so I remove the corresponding values there. IIRC, the only stuff not covered by `FUNDING.yml` is crypto currencies, so those we'd need to leave in if there're any.

> 1.46.16 tag was for testing/experimenting

Ah, OK. So a new one is to be expected soon?

**Comment by adbenitez** [comment]
> Ah, OK. So a new one is to be expected soon?

hi, there is a new version tagged since 3 days ago but still not showing in IoD, with the new version the anti-features should be gone since it is FOSS version, sorry if there was some manual action needed on your side and you was waiting for me to notify you about the new tag here

**Comment by IzzySoft** [comment]
> but still not showing in IoD

No. Because the tag name pattern changed at your Github releases. Our updater was only checking tags going by the pattern `v%v-deltalab`, with `%v` being the `versionName`. Since 1.46.14, the naming pattern changed to `v%v` – so no new tags were found. I've just updated that in the metadata here right now (updater is currently running, so I triggered the pull manually to have it hopefully be included when the index is being built :crossed_fingers:). Grmpf, looks like I was a minute or so too late, so it will show up with the next sync then.

**Comment by adbenitez** [comment]
thanks a lot! :heart:

**Comment by IzzySoft** [comment]
Gladly – thanks for the ping!

**Comment by adbenitez** [comment]
> (FUNDING.yml) that file will be checked for on each release. But as its values are overwritten by what's explicitly specified in the app's metadata, please let me know when you've set it up so I remove the corresponding values there. IIRC, the only stuff not covered by `FUNDING.yml` is crypto currencies, so those we'd need to leave in if there're any.

hi @IzzySoft I have finally added the FUNDING.yml file, and as you requested I am letting you know so you remove the manual values, thanks a lot in advance!

**Comment by IzzySoft** [comment]
Thanks a lot! I just wonder if OpenCollective is really gone? What we had here (and I'll remove now to leave it to your `FUNDING.yml`) is:

```yaml
Donate: https://delta.chat/en/contribute#donate-money-or-devices
Liberapay: delta.chat
OpenCollective: delta-chat
```

`FUNDING.yml` is now in place (effective with the next sync):

```
$ iod repo fastlane chat.delta.lite
chat.delta.lite: check if repo contains FUNDING.yml
chat.delta.lite: looking for 'https://api.github.com/repos/ArcaneChat/android/contents/.github'
chat.delta.lite: replacing 'build/chat.delta.lite/FUNDING.yml'
chat.delta.lite: calling 'getFastlaneMeta(github,[host:github.com,owner:ArcaneChat,repo:android,path:/fastlane/metadata/android])'
chat.delta.lite: FastlaneFeatures title,shortdesc,fulldescMD,screenshotsJPG,icon,featureGraphicJPG
chat.delta.lite: looking for 'https://api.github.com/repos/ArcaneChat/android/contents/fastlane%2Fmetadata%2Fandroid'
chat.delta.lite: looking for 'https://api.github.com/repos/ArcaneChat/android/contents/fastlane%2Fmetadata%2Fandroid%2Fen-US'
chat.delta.lite: looking for 'https://api.github.com/repos/ArcaneChat/android/contents/fastlane%2Fmetadata%2Fandroid%2Fen-US%2Fimages'
chat.delta.lite: looking for 'https://api.github.com/repos/ArcaneChat/android/contents/fastlane%2Fmetadata%2Fandroid%2Fen-US%2Fimages%2FphoneScreenshots'
chat.delta.lite: checking locale 'en-US'
chat.delta.lite: updating 'repo/chat.delta.lite/en-US/featureGraphic.jpg' from 'featureGraphic.png'
chat.delta.lite: updating 'repo/chat.delta.lite/en-US/phoneScreenshots/1.png' as JPG
chat.delta.lite: updating 'repo/chat.delta.lite/en-US/phoneScreenshots/2.png' as JPG
chat.delta.lite: updating 'repo/chat.delta.lite/en-US/phoneScreenshots/3.png' as JPG
chat.delta.lite: updating 'repo/chat.delta.lite/en-US/phoneScreenshots/4.png' as JPG
chat.delta.lite: updating 'repo/chat.delta.lite/en-US/phoneScreenshots/5.png' as JPG
chat.delta.lite: cross-checking for obsolete screenshots
chat.delta.lite: screenshots in Fastlane: 1,2,3,4,5
chat.delta.lite: local screenshots checked: 1,2,3,4,5
```

**Comment by adbenitez** [comment]
> Thanks a lot! I just wonder if OpenCollective is really gone? What we had here (and I'll remove now to leave it to your `FUNDING.yml`) is:

now that ArcaneChat provides his own server, makes sense to collect donations directly to support keeping the server running, where the `Donate:` comes from? the ArcaneChat contributing page link is https://arcanechat.me/#contribute

**Comment by IzzySoft** [comment]
> where the `Donate:` comes from?

I don't remember, sorry 🙈 But it's removed now; donation info now is only taken from your `FUNDING.yml`.

> I don't have OpenCollective account

Ah, OK. Then its "being gone" makes sense. Should you one day create an OC account for ArcaneChat, you can simply add it to your `FUNDING.yml` and it will be picked up with the next release.

Thanks for clarification!
