### ISSUE TITLE
Monochrome/Themed App Icon

### ISSUE THREAD

**Issue by NielSync** [deltalab-org/deltalab-android#21]
![Screenshot_20240629-185003.jpg](https://github.com/deltalab-org/deltalab-android/assets/20804647/39475ebb-78bb-4389-94ac-3451af51963b)

**Comment by adbenitez** [comment]
thanks for your request, it seems this is also part of "Material You" (related issue #18) 

the steps to implement this are here:
https://developer.android.com/about/versions/13/features#themed-app-icons

seems to be doable

**Comment by adbenitez** [comment]
(offtopic: I am not sure about the moves of google with these monochrome icons, doesn't it make it harder to recognize app icons?)

**Comment by adbenitez** [comment]
@NielSync your feature request was added :tada: you will be able to enjoy it in the next release, thanks!
